[pytest]
testpaths = test_runner
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=reports/allure-results
markers =
    smoke: 冒烟测试用例
    posts: 文章模块
    positive: 正向场景
    negative: 异常场景
    users: 用户模块
    reqres: Reqres测试接口
